(let ([x (vector 1 2 3)])
  (let ([y (vector 4 5 6)])
	(let ([z (vector x y)])
	  (let ([v (vector z z)])
		(let ([_ (vector-set! (vector-ref (vector-ref v 0) 0) 0 42)])
		  (let ([_ (vector-set! (vector-ref (vector-ref v 1) 1) 1 10)])
			(+ (vector-ref x 0) (vector-ref y 1))))))))
